trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Scan
    jobs:
      - job: Scan_Secrets
        displayName: Scan secrets
        steps:
          - checkout: self
            fetchDepth: 0
          - task: Gitleaks@3
            inputs:
              scanlocation: '$(Build.SourcesDirectory)'
              configtype: 'predefined'
              predefinedconfigfile: 'GitleaksUdmCombo.toml'
              reportformat: 'sarif'